version: "3.7"

services:
  client:
    container_name: client
    build:
      context: ./
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_API_URL=$REACT_APP_API_URL
    ports:
      - "3001:80"
